services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-fe
    ports:
      - '3000:3000'
    environment:
      NEXTAUTH_SECRET: 'vfy5CdtSFMFqELUvIGMY0oaYmUIY4prixBeRdZ8t0no'
      NEXTAUTH_URL: 'http://localhost:3000'
      NEXT_PUBLIC_API_URL: 'http://localhost:5000/api'

networks:
  task-management-network:
    external: true
