services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-management-fe
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: 'http://localhost:5000'
